const Data = {
  data: [
    {
      tno: "1",
      timage: "",
      tname: "축제",
      taddr: "서울특별시",
      tcategory: "축제",
    },
    { tno: "2", timage: "", tname: "축제", taddr: "경기도", tcategory: "축제" },
    { tno: "3", timage: "", tname: "축제", taddr: "강원도", tcategory: "축제" },
    {
      tno: "4",
      timage: "",
      tname: "축제",
      taddr: "충청북도",
      tcategory: "축제",
    },
    {
      tno: "5",
      timage: "",
      tname: "축제",
      taddr: "경상북도",
      tcategory: "축제",
    },
    {
      tno: "6",
      timage: "",
      tname: "축제",
      taddr: "세종특별자치시",
      tcategory: "축제",
    },
    {
      tno: "7",
      timage: "",
      tname: "축제",
      taddr: "대전광역시",
      tcategory: "축제",
    },
    {
      tno: "8",
      timage: "",
      tname: "축제",
      taddr: "충청남도",
      tcategory: "축제",
    },
    {
      tno: "9",
      timage: "",
      tname: "축제",
      taddr: "전북특별자치도",
      tcategory: "축제",
    },
    {
      tno: "10",
      timage: "",
      tname: "축제",
      taddr: "전라남도",
      tcategory: "축제",
    },
    {
      tno: "11",
      timage: "",
      tname: "축제",
      taddr: "광주광역시",
      tcategory: "축제",
    },
    {
      tno: "12",
      timage: "",
      tname: "축제",
      taddr: "경상남도",
      tcategory: "축제",
    },
    {
      tno: "13",
      timage: "",
      tname: "축제",
      taddr: "대구광역시",
      tcategory: "축제",
    },
    {
      tno: "14",
      timage: "",
      tname: "축제",
      taddr: "울산광역시",
      tcategory: "축제",
    },
    {
      tno: "15",
      timage: "",
      tname: "축제",
      taddr: "부산광역시",
      tcategory: "축제",
    },
    {
      tno: "16",
      timage: "",
      tname: "축제",
      taddr: "제주특별자치도",
      tcategory: "축제",
    },
    {
      tno: "17",
      timage: "",
      tname: "숙박",
      taddr: "서울특별시",
      tcategory: "숙박",
    },
    {
      tno: "18",
      timage: "",
      tname: "숙박",
      taddr: "경기도",
      tcategory: "숙박",
    },
    {
      tno: "19",
      timage: "",
      tname: "숙박",
      taddr: "강원도",
      tcategory: "숙박",
    },
    {
      tno: "20",
      timage: "",
      tname: "숙박",
      taddr: "충청북도",
      tcategory: "숙박",
    },
    {
      tno: "21",
      timage: "",
      tname: "숙박",
      taddr: "경상북도",
      tcategory: "숙박",
    },
    {
      tno: "22",
      timage: "",
      tname: "숙박",
      taddr: "세종특별자치시",
      tcategory: "숙박",
    },
    {
      tno: "23",
      timage: "",
      tname: "숙박",
      taddr: "대전광역시",
      tcategory: "숙박",
    },
    {
      tno: "24",
      timage: "",
      tname: "숙박",
      taddr: "충청남도",
      tcategory: "숙박",
    },
    {
      tno: "25",
      timage: "",
      tname: "숙박",
      taddr: "전북특별자치도",
      tcategory: "숙박",
    },
    {
      tno: "26",
      timage: "",
      tname: "숙박",
      taddr: "전라남도",
      tcategory: "숙박",
    },
    {
      tno: "27",
      timage: "",
      tname: "숙박",
      taddr: "광주광역시",
      tcategory: "숙박",
    },
    {
      tno: "28",
      timage: "",
      tname: "숙박",
      taddr: "경상남도",
      tcategory: "숙박",
    },
    {
      tno: "29",
      timage: "",
      tname: "숙박",
      taddr: "대구광역시",
      tcategory: "숙박",
    },
    {
      tno: "30",
      timage: "",
      tname: "숙박",
      taddr: "울산광역시",
      tcategory: "숙박",
    },
    {
      tno: "31",
      timage: "",
      tname: "숙박",
      taddr: "부산광역시",
      tcategory: "숙박",
    },
    {
      tno: "32",
      timage: "",
      tname: "숙박",
      taddr: "제주특별자치도",
      tcategory: "숙박",
    },
    {
      tno: "33",
      timage: "",
      tname: "맛집",
      taddr: "서울특별시",
      tcategory: "맛집",
    },
    {
      tno: "34",
      timage: "",
      tname: "맛집",
      taddr: "경기도",
      tcategory: "맛집",
    },
    {
      tno: "35",
      timage: "",
      tname: "맛집",
      taddr: "강원도",
      tcategory: "맛집",
    },
    {
      tno: "36",
      timage: "",
      tname: "맛집",
      taddr: "충청북도",
      tcategory: "맛집",
    },
    {
      tno: "37",
      timage: "",
      tname: "맛집",
      taddr: "경상북도",
      tcategory: "맛집",
    },
    {
      tno: "38",
      timage: "",
      tname: "맛집",
      taddr: "세종특별자치시",
      tcategory: "맛집",
    },
    {
      tno: "39",
      timage: "",
      tname: "맛집",
      taddr: "대전광역시",
      tcategory: "맛집",
    },
    {
      tno: "40",
      timage: "",
      tname: "맛집",
      taddr: "충청남도",
      tcategory: "맛집",
    },
    {
      tno: "41",
      timage: "",
      tname: "맛집",
      taddr: "전북특별자치도",
      tcategory: "맛집",
    },
    {
      tno: "42",
      timage: "",
      tname: "맛집",
      taddr: "전라남도",
      tcategory: "맛집",
    },
    {
      tno: "43",
      timage: "",
      tname: "맛집",
      taddr: "광주광역시",
      tcategory: "맛집",
    },
    {
      tno: "44",
      timage: "",
      tname: "맛집",
      taddr: "경상남도",
      tcategory: "맛집",
    },
    {
      tno: "45",
      timage: "",
      tname: "맛집",
      taddr: "대구광역시",
      tcategory: "맛집",
    },
    {
      tno: "46",
      timage: "",
      tname: "맛집",
      taddr: "울산광역시",
      tcategory: "맛집",
    },
    {
      tno: "47",
      timage: "",
      tname: "맛집",
      taddr: "부산광역시",
      tcategory: "맛집",
    },
    {
      tno: "48",
      timage: "",
      tname: "맛집",
      taddr: "제주특별자치도",
      tcategory: "맛집",
    },
  ],
};
export default Data;
